### Send POST request with json body
PUT http://localhost:8080/developer/Son
Content-Type: application/json

{
  "developerLevel": "JUNGNIOR",
  "developerSkillType": "FULL_STACK",
  "experienceYears": 6
}